import { expect, test } from '@playwright/test'

async function enterCleanroom(page: import('@playwright/test').Page) {
  await expect(page.getByRole('heading', { name: '환영합니다' })).toBeVisible()
  await page.getByRole('button', { name: /출입 등록 시작/ }).click()
  await expect(page.getByRole('heading', { name: '손 씻기' })).toBeVisible()
  await page.getByRole('button', { name: /세정 완료/ }).click()
  await expect(page.getByRole('heading', { name: '마스크 착용' })).toBeVisible()
  if ((page.viewportSize()?.width ?? 0) > 760) {
    const guideBox = await page.locator('.guide-dialog').boundingBox()
    const viewportWidth = page.viewportSize()?.width ?? 0
    expect(guideBox).not.toBeNull()
    expect((guideBox?.x ?? 0) + (guideBox?.width ?? 0)).toBeLessThan(viewportWidth * 0.49)
    const stageFontSize = await page.locator('.entry-progress b').first().evaluate((element) => parseFloat(getComputedStyle(element).fontSize))
    expect(stageFontSize).toBeGreaterThanOrEqual(12)
  }
  await page.getByRole('button', { name: /마스크 착용/ }).click()
  await expect(page.getByRole('heading', { name: '방진복 착용' })).toBeVisible()
  await page.getByRole('button', { name: /방진복 착용/ }).click()
  await expect(page.getByRole('heading', { name: '에어샤워 통과' })).toBeVisible()
  await page.getByRole('button', { name: /에어샤워 가동/ }).click()
  await expect(page.getByRole('heading', { name: /사건이 기다리는 공정룸/ })).toBeVisible({ timeout: 12_000 })
}

test('complete the evidence-led scenario', async ({ page }, testInfo) => {
  test.setTimeout(300_000)
  const errors: string[] = []
  page.on('console', (message) => { if (message.type() === 'error') errors.push(message.text()) })
  await page.goto('/#photo-cd-drift')
  await expect(page.getByText('사라진 선폭의 비밀')).toBeVisible()
  await expect(page.getByText('CASE VF-PH-01')).toBeVisible()
  await expect(page.getByText('후속 Etch 투입까지 60분')).toBeVisible()
  await expect(page.locator('.station-tag')).toHaveCount(5)
  await expect(page.getByText('FAB ROOKIE', { exact: true })).toBeVisible()
  await expect(page.locator('.mission-hud')).toContainText('MISSION 01')
  await page.waitForTimeout(800)
  await page.screenshot({ path: testInfo.outputPath('first-viewport.png'), fullPage: true })

  if (testInfo.project.name === 'mobile') {
    await expect(page.locator('.workbench')).toBeVisible()
    await expect(page.getByRole('separator', { name: '3D 화면과 작업창 너비 조절' })).toBeHidden()
    await page.getByRole('button', { name: /Lot 보류/ }).click()
    await page.getByRole('button', { name: /판단을 기록하고/ }).click()
    await expect(page.getByRole('heading', { name: '데이터·AI 공동분석' })).toBeVisible()
    await expect(page.getByRole('button', { name: '서버 CSV 불러오기·미리보기' })).toBeVisible()
    await expect(page.getByRole('heading', { name: '내 AI 연결' })).toBeVisible()
    await expect(page.getByRole('region', { name: '다음 단계 진행 조건' })).toContainText('1/4 완료')
    await expect(page.getByRole('button', { name: '다음 단계 조건 3개 남음' })).toBeDisabled()
    await page.getByRole('button', { name: '서버 CSV 불러오기·미리보기' }).click()
    await expect(page.getByRole('region', { name: '분포를 눈으로 검증' })).toBeVisible()
    await page.screenshot({ path: testInfo.outputPath('mobile-data-evidence.png'), fullPage: true })
    expect(errors).toEqual([])
    return
  }

  await page.getByRole('button', { name: /Lot 보류/ }).click()
  await page.getByRole('button', { name: /판단을 기록하고/ }).click()
  await expect(page.getByRole('heading', { name: '데이터·AI 공동분석' })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: '데이터·AI 공동분석' })).toBeVisible()
  await expect(page.getByText('이전 실험을 복원했어.')).toBeVisible()
  await page.getByRole('button', { name: /EVIDENCE/ }).click()
  await expect(page.getByRole('dialog', { name: 'Evidence trail' })).toContainText('판정 보류 후 분포 확인')
  await page.getByRole('button', { name: 'Evidence 닫기' }).click()
  await expect(page.getByText('DATA · AI INVESTIGATION', { exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: '내 AI 연결' })).toBeVisible()
  await expect(page.getByLabel('AI 제공사')).toHaveValue('gemini')
  await expect(page.getByLabel('개인 API 키')).toHaveAttribute('type', 'password')
  await expect(page.getByLabel('개인 API 키')).toBeEnabled()
  await expect(page.getByText('HTTPS 연결 필요')).toHaveCount(0)
  await expect(page.getByRole('button', { name: '1. 연결 확인' })).toBeDisabled()
  await expect(page.getByRole('button', { name: '2. 질문 보내기' })).toBeDisabled()
  await expect(page.locator('.question-strategy > ol > li')).toHaveCount(5)
  await expect(page.locator('.keyword-library button')).toHaveCount(6)
  await expect(page.getByText('용어·데이터 이해', { exact: true }).first()).toBeVisible()
  await page.getByRole('button', { name: '선택 키워드로 질문 초안 만들기' }).click()
  await expect(page.getByLabel('AI에게 물어볼 다음 질문')).toHaveValue(/\[핵심 키워드\] CD, Dose/)
  await expect(page.getByText(/전송 준비 · 포함 키워드: CD, Dose/)).toBeVisible()
  await page.getByRole('button', { name: '서버 CSV 불러오기·미리보기' }).click()
  await expect(page.getByRole('table', { name: '현재 세션 합성 CSV의 첫 200행 미리보기' })).toBeVisible()
  await expect(page.locator('.dataset-preview thead th')).toHaveCount(10)
  await expect(page.locator('.dataset-preview tbody tr')).toHaveCount(200)
  await expect(page.getByText('미리보기 완료 · 2969행 × 10열')).toBeVisible()
  await expect(page.getByRole('region', { name: '합성 데이터 그룹 집계' })).toContainText('radius_mm bin')
  const dataVisual = page.getByRole('region', { name: '분포를 눈으로 검증' })
  await expect(dataVisual).toBeVisible()
  await expect(dataVisual).toContainText(/전체\s*2969/)
  await expect(dataVisual).toContainText(/결측\s*\d+/)
  await expect(dataVisual).toContainText(/단위 오류\s*\d+/)
  await expect(dataVisual).toContainText(/중복\s*\d+/)
  const datasetDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'CSV 파일로 저장' }).click()
  expect((await datasetDownload).suggestedFilename()).toContain('virtual-fab-photo-cd-drift')
  await expect(page.getByText('AI 데이터 자동 연결됨')).toBeVisible()
  await expect(page.getByText(/브라우저 보안상 PC의 Downloads 폴더 경로는 찾거나 읽지 않아/)).toBeVisible()
  await expect(page.locator('.dataset-ai-note code')).toContainText(`/api/sessions/`)
  await expect(page.getByLabel('AI에게 물어볼 다음 질문')).toHaveValue(/서버 CSV 원문 전체와 통계 요약을 자동 첨부함/)
  await expect(page.getByRole('button', { name: '개인 키 없이 외부 AI용 질문 복사' })).toBeVisible()
  const manualAnswer = '가설 1은 Dose 변화, 가설 2는 Focus 변화, 가설 3은 측정 편향입니다. 합성 CSV의 CENTER·EDGE와 Tool·Lot 분포를 대조해 반증합니다.'
  for (let turn = 1; turn <= 8; turn += 1) {
    await page.getByLabel('외부 AI 분석 답변 붙여넣기').fill(`${manualAnswer} 현재는 ${turn}회차 분석입니다.`)
    await page.getByRole('button', { name: '현재 질문·답변을 문답 기록에 추가' }).click()
  }
  await expect(page.getByText('심층 분석 완료 조건 충족')).toBeVisible()
  await expect(page.getByText('8/8 필수 · 7회 추가 사용 가능')).toBeVisible()
  const evidenceNotebook = page.getByRole('region', { name: 'STEP 2 · AI 문답 증거 노트' })
  await expect(evidenceNotebook).toContainText('질문 → 응답 → 사람 검증 → 다음 판단')
  await evidenceNotebook.getByRole('button', { name: '채택' }).first().click()
  await evidenceNotebook.getByLabel('Q1 사람 검증').getByLabel('검증 근거').fill('radius bin 평균과 결측 집계를 직접 대조했다.')
  await expect(evidenceNotebook.getByRole('button', { name: '채택' }).first()).toHaveAttribute('aria-pressed', 'true')
  const noteDownload = page.waitForEvent('download')
  await evidenceNotebook.getByRole('button', { name: '현재 분석노트 MD' }).click()
  expect((await noteDownload).suggestedFilename()).toContain('analysis-note.md')
  await page.screenshot({ path: testInfo.outputPath('external-ai-stage.png'), fullPage: true })
  await page.getByLabel('원인 Tool').selectOption('PHOTO_A')
  await page.getByLabel('이상 영역').selectOption('edge')
  await page.getByLabel('Drift 시작 Lot').fill('LOT-005')
  await page.getByLabel('결측 행 수').fill('99')
  await page.getByLabel('단위오류 행 수').fill('44')
  await page.getByLabel('중복 행 수').fill('29')
  await page.getByLabel('미끼 Tool 배제 근거').fill('PHOTO_B는 전면 균일 shift라 결함과 무관하다.')
  await page.getByRole('button', { name: '분포·품질 근거로 판단' }).click()
  await page.getByRole('button', { name: /데이터·AI 문답·내 판단을 저장하고/ }).click()
  await expect(page.getByText('SCREENING DOE', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: /EVIDENCE/ }).click()
  await page.getByText('데이터 다운로드 · AI 문답 8회').click()
  await expect(page.getByRole('dialog', { name: 'Evidence trail' })).toContainText('[핵심 키워드] CD, Dose')
  await expect(page.getByRole('dialog', { name: 'Evidence trail' })).toContainText('KEYWORDS · CD · Dose')
  await expect(page.getByRole('dialog', { name: 'Evidence trail' })).toContainText('가설 1은 Dose 변화')
  await expect(page.getByRole('dialog', { name: 'Evidence trail' })).toContainText('HUMAN REVIEW · 채택')
  await expect(page.getByRole('dialog', { name: 'Evidence trail' })).toContainText('radius bin 평균과 결측 집계를 직접 대조했다.')
  await page.getByRole('button', { name: 'Evidence 닫기' }).click()
  await page.getByRole('button', { name: /대조군.*Screening/ }).click()
  await page.getByRole('button', { name: /판단을 기록하고/ }).click()
  await expect(page.getByText('ANALYSIS TOOL BAY', { exact: true })).toBeVisible()
  await expect(page.getByRole('region', { name: '예산 시간 신뢰도 비교' })).toContainText('필수 정보영역2/2')
  await expect(page.getByRole('region', { name: '예산 시간 신뢰도 비교' })).toContainText('예상 증거 신뢰도87%')
  await expect(page.getByRole('region', { name: '예산 시간 신뢰도 비교' })).toContainText('광학현미경 · Optical CD + SEM · 19C · 13m')
  await page.screenshot({ path: testInfo.outputPath('analysis-stage.png'), fullPage: true })
  await page.getByRole('button', { name: /이 분석 조합/ }).click()
  await page.getByRole('button', { name: /판단을 기록하고/ }).click()
  await expect(page.getByText('HOLDOUT GATE', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: /한정 적용/ }).click()
  await page.getByRole('button', { name: /판단을 기록하고/ }).click()
  await expect(page.getByText('시나리오 해결 · 입력 증거 기준')).toBeVisible()
  const competency = page.getByRole('region', { name: '역량 증거 리포트' })
  await expect(competency.locator('header strong')).toHaveText(/^\d+\/ 100$/)
  await expect(competency).toContainText(/데이터·증거 품질\d+\/30/)
  await expect(competency).toContainText('사람 판정1회')
  await expect(competency).toContainText('학습 향상 점수가 아닙니다')
  const finalNoteDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: '전체 조사 기록 Markdown' }).click()
  expect((await finalNoteDownload).suggestedFilename()).toContain('final-record.md')
  await page.getByLabel('내 판단·배운 점·한계').fill('평균값만 보지 않고 위치별 분포와 대안 가설을 확인한 뒤 최소 분석으로 검증하는 접근이 중요하다고 판단했다.')
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: /HTML 면접 PT 슬라이드/ }).click()
  const download = await downloadPromise
  expect(download.suggestedFilename()).toBe('virtual-fab-interview-slides.html')
  await page.screenshot({ path: testInfo.outputPath('complete.png'), fullPage: true })
  expect(errors).toEqual([])
})

test('open a new dry etch case from the module home', async ({ page }) => {
  await page.goto('/')
  await page.screenshot({ path: test.info().outputPath('cleanroom-entry.png'), fullPage: true })
  await enterCleanroom(page)
  await page.screenshot({ path: test.info().outputPath('process-hall.png'), fullPage: true })
  await expect(page.locator('.module-card')).toHaveCount(6)
  await page.getByRole('button', { name: 'DRY ETCH 기울어진 Sidewall 시나리오 시작' }).click()
  await expect(page.getByText('기울어진 Sidewall')).toBeVisible()
  await expect(page.getByText('CASE VF-DE-02')).toBeVisible()
  await expect(page.getByText('119.8 nm')).toBeVisible()
  await expect(page.getByRole('button', { name: /Profile·위치 분포부터 확인/ })).toBeVisible()
})

test('preview server CSV in every process scenario', async ({ page }) => {
  const scenarios = [
    ['photo-cd-drift', 'PHOTO'],
    ['dry-etch-profile', 'DRY ETCH'],
    ['sputter-sheet-resistance', 'SPUTTER'],
    ['cvd-film-uniformity', 'CVD'],
    ['cmp-dishing', 'CMP'],
    ['device-vth-shift', 'DEVICE'],
  ] as const

  for (const [scenarioId, process] of scenarios) {
    await page.goto(`/#${scenarioId}`)
    await page.locator('.choice-grid .choice').first().click()
    await page.getByRole('button', { name: /판단을 기록하고/ }).click()
    await expect(page.getByRole('heading', { name: '데이터·AI 공동분석' })).toBeVisible()
    await page.getByRole('button', { name: '서버 CSV 불러오기·미리보기' }).click()
    await expect(page.getByText(`CSV DATA PREVIEW · ${process}`)).toBeVisible()
    await expect(page.locator('.dataset-preview thead th')).toHaveCount(scenarioId === 'photo-cd-drift' ? 10 : 9)
    await expect(page.locator('.dataset-preview tbody tr')).toHaveCount(scenarioId === 'photo-cd-drift' ? 200 : 42)
    await expect(page.getByText('AI 데이터 자동 연결됨')).toBeVisible()
  }
})

test('return to a completed stage from the top step rail', async ({ page }) => {
  await page.goto('/#sputter-sheet-resistance')
  await page.getByRole('button', { name: /Lot 보류/ }).click()
  await page.getByRole('button', { name: /판단을 기록하고/ }).click()
  await expect(page.getByRole('heading', { name: '데이터·AI 공동분석' })).toBeVisible()
  await page.getByRole('button', { name: /문제 발생 단계로 돌아가기/ }).click()
  await expect(page.getByText('CASE VF-SP-03')).toBeVisible()
  await expect(page.getByText('문제 발생 단계로 돌아왔어. 이후 판단 1개를 되돌렸고')).toBeVisible()
  await expect(page.getByRole('button', { name: /EVIDENCE/ })).toContainText('0')
})

test('resize and persist the desktop visual and workbench split', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name === 'mobile', '데스크톱 전용 분할바')
  await page.goto('/#photo-cd-drift')
  const workspace = page.locator('.workspace')
  const visual = page.locator('.visual-column')
  const workbench = page.locator('.workbench')
  const resizer = page.getByRole('separator', { name: '3D 화면과 작업창 너비 조절' })
  const workspaceBox = await workspace.boundingBox()
  const initialVisualBox = await visual.boundingBox()
  const initialWorkbenchBox = await workbench.boundingBox()
  const resizerBox = await resizer.boundingBox()
  expect(workspaceBox && initialVisualBox && initialWorkbenchBox && resizerBox).toBeTruthy()
  expect((initialVisualBox?.width ?? 0) / (workspaceBox?.width ?? 1)).toBeGreaterThan(0.46)
  expect((initialVisualBox?.width ?? 0) / (workspaceBox?.width ?? 1)).toBeLessThan(0.5)

  await page.mouse.move((resizerBox?.x ?? 0) + (resizerBox?.width ?? 0) / 2, (resizerBox?.y ?? 0) + 120)
  await page.mouse.down()
  await page.mouse.move((workspaceBox?.x ?? 0) + (workspaceBox?.width ?? 0) * 0.38, (resizerBox?.y ?? 0) + 120)
  await page.mouse.up()
  await expect(resizer).toHaveAttribute('aria-valuenow', /3[78]/)
  const narrowedVisualBox = await visual.boundingBox()
  const widenedWorkbenchBox = await workbench.boundingBox()
  expect(narrowedVisualBox?.width ?? 0).toBeLessThan(initialVisualBox?.width ?? 0)
  expect(widenedWorkbenchBox?.width ?? 0).toBeGreaterThan(initialWorkbenchBox?.width ?? 0)
  await page.screenshot({ path: testInfo.outputPath('resized-workspace.png'), fullPage: true })

  await page.reload()
  await expect(page.getByRole('separator', { name: '3D 화면과 작업창 너비 조절' })).toHaveAttribute('aria-valuenow', /3[78]/)
  await page.getByRole('separator', { name: '3D 화면과 작업창 너비 조절' }).dblclick()
  await expect(page.getByRole('separator', { name: '3D 화면과 작업창 너비 조절' })).toHaveAttribute('aria-valuenow', '48')
  await page.getByRole('separator', { name: '3D 화면과 작업창 너비 조절' }).press('ArrowRight')
  await expect(page.getByRole('separator', { name: '3D 화면과 작업창 너비 조절' })).toHaveAttribute('aria-valuenow', '50')
})

test('explore companies in the semiconductor and display dual galaxy', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name === 'mobile', '데스크톱 3D 노드 탐색은 데스크톱 프로젝트에서 확인')
  const errors: string[] = []
  page.on('console', (message) => { if (message.type() === 'error') errors.push(message.text()) })
  await page.goto('/industry-map/')
  await expect(page.getByRole('heading', { name: '반도체 × 디스플레이 산업 은하' })).toBeVisible()
  await expect(page.getByLabel('반도체와 디스플레이 산업 3D 지식맵')).toContainText('73 / 73 COMPANIES')
  await expect(page.getByRole('heading', { name: 'SK hynix' })).toBeVisible()
  await expect(page.getByText('심층분석 완료')).toBeVisible()
  await expect(page.getByText('16H · 48GB', { exact: true })).toBeVisible()
  await expect(page.getByText('공개 관계 강도 4/5', { exact: false }).first()).toBeVisible()
  await expect(page.getByText('실제 거래금액 비중은 공개된 경우에만 표시해.')).toBeVisible()
  await expect(page.getByLabel('산업·업종·매출 범례')).toContainText('행성 크기 = 최근 공개 연매출')
  await expect(page.getByLabel('산업·업종·매출 범례')).toContainText('공정 장비')
  await expect(page.getByLabel('산업·업종·매출 범례')).toContainText('세트·고객·설계')
  await expect(page.getByLabel('산업·업종·매출 범례')).toContainText('재료·핵심부품')
  await expect(page.getByLabel('행성 크기 기준')).toContainText('연매출 $10B–50B')
  await expect(page.getByText('Z축 4단 공급망 · 대형회사명 표시')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Duksan Neolux 상세보고서 열기' })).toHaveCount(0)
  await page.getByRole('button', { name: '회사 목록' }).click()
  await page.getByLabel('산업 지식맵 회사 목록').getByRole('button', { name: /Duksan Neolux/ }).click()
  await page.getByRole('button', { name: '3D 은하' }).click()
  await expect(page.getByRole('button', { name: 'Duksan Neolux 상세보고서 열기' })).toBeVisible()
  await page.getByRole('button', { name: '회사 목록' }).click()
  await page.getByLabel('산업 지식맵 회사 목록').getByRole('button', { name: /SK hynix/ }).click()
  await page.getByRole('button', { name: '공정 장비표' }).click()
  await expect(page.getByRole('heading', { name: '공정별 장비·소재 생태계' })).toBeVisible()
  await expect(page.getByText('기준연도가 표시되지 않았어', { exact: false })).toBeVisible()
  await expect(page.getByRole('row')).toHaveCount(11)
  await page.getByRole('button', { name: 'Flexible OLED' }).click()
  await expect(page.getByText('PI Varnish', { exact: true })).toBeVisible()
  await expect(page.getByRole('table', { name: 'Flexible OLED 공정별 장비와 소재 공급사 참고자료' })).toContainText('Canon Tokki')
  await expect(page.getByText('신한금융투자', { exact: false })).toBeVisible()
  await expect(page.getByRole('row')).toHaveCount(19)
  await page.getByRole('button', { name: '3D 은하' }).click()
  const selectedMapLabel = page.getByRole('button', { name: 'SK hynix 상세보고서 열기' })
  await expect(selectedMapLabel).toBeVisible()
  const selectedLabelFontSize = await selectedMapLabel.locator('b').evaluate((element) => Number.parseFloat(getComputedStyle(element).fontSize))
  expect(selectedLabelFontSize).toBeGreaterThanOrEqual(12)
  const pauseOrbit = page.getByRole('button', { name: '공전 일시정지' })
  if (await pauseOrbit.isVisible()) await pauseOrbit.click()
  await expect(page.getByRole('button', { name: '공전 시작' })).toBeVisible()
  const orbitStart = await selectedMapLabel.boundingBox()
  await page.getByRole('button', { name: '공전 시작' }).click()
  await expect(page.getByRole('button', { name: '공전 일시정지' })).toBeVisible()
  await page.waitForTimeout(2600)
  const orbitEnd = await selectedMapLabel.boundingBox()
  expect(Math.abs((orbitEnd?.x ?? 0) - (orbitStart?.x ?? 0)) + Math.abs((orbitEnd?.y ?? 0) - (orbitStart?.y ?? 0))).toBeGreaterThan(.5)
  await page.getByRole('button', { name: '공전 일시정지' }).click()
  const ordinaryMapLabel = page.getByRole('button', { name: 'ASML 상세보고서 열기' })
  await expect(ordinaryMapLabel).toBeVisible()
  await expect(ordinaryMapLabel.locator('b')).toHaveCSS('font-size', '12px')
  await expect(ordinaryMapLabel.locator('span')).toBeHidden()
  await page.screenshot({ path: testInfo.outputPath('industry-map.png') })
  const selectCompanyFromList = async (name: RegExp) => {
    await page.getByRole('button', { name: '회사 목록' }).click()
    await page.getByLabel('산업 지식맵 회사 목록').getByRole('button', { name }).click()
    await page.getByRole('button', { name: '3D 은하' }).click()
  }
  await selectCompanyFromList(/Samsung Electronics/)
  await expect(page.getByRole('heading', { name: 'Samsung Electronics' })).toBeVisible()
  await expect(page.getByText('최대 3.3TB/s', { exact: true })).toBeVisible()
  await expect(page.getByText('2030년까지 5년간 $200B+', { exact: false })).toBeVisible()
  await selectCompanyFromList(/Micron/)
  await expect(page.getByRole('heading', { name: 'Micron' })).toBeVisible()
  await expect(page.getByText('>1.2TB/s', { exact: true })).toBeVisible()
  await selectCompanyFromList(/Applied Materials/)
  await expect(page.getByRole('heading', { name: 'Applied Materials' })).toBeVisible()
  await expect(page.getByText('$9.115B', { exact: true })).toBeVisible()
  await expect(page.getByText('두 은하의 공통 노드')).toBeVisible()
  await page.getByLabel('산업 은하', { exact: true }).selectOption('display')
  await expect(page.getByLabel('반도체와 디스플레이 산업 3D 지식맵')).toContainText('14 / 73 COMPANIES')
  await selectCompanyFromList(/ICD/)
  await expect(page.getByRole('heading', { name: 'ICD' })).toBeVisible()
  await expect(page.getByText('OLED·LCD ICP Dry Etcher', { exact: true })).toBeVisible()
  await selectCompanyFromList(/Samsung Display/)
  await expect(page.getByRole('heading', { name: 'Samsung Display' })).toBeVisible()
  await expect(page.getByText('8.6G', { exact: true })).toBeVisible()
  await page.getByLabel('산업 은하', { exact: true }).selectOption('shared')
  await expect(page.getByLabel('반도체와 디스플레이 산업 3D 지식맵')).toContainText('16 / 73 COMPANIES')
  await selectCompanyFromList(/Dongjin Semichem/)
  await expect(page.getByRole('heading', { name: 'Dongjin Semichem' })).toBeVisible()
  await expect(page.getByText('반도체·디스플레이 감광·습식 공정소재', { exact: true })).toBeVisible()
  await expect(page.locator('.industry-report')).toContainText('중국 LCD·OLED 공정 화학소재 공급')
  await page.getByLabel('산업 은하', { exact: true }).selectOption('all')
  await page.getByLabel('본사 지역').selectOption('korea')
  await expect(page.getByLabel('반도체와 디스플레이 산업 3D 지식맵')).toContainText('19 / 73 COMPANIES')
  await page.getByLabel('본사 지역').selectOption('china')
  await expect(page.getByLabel('반도체와 디스플레이 산업 3D 지식맵')).toContainText('7 / 73 COMPANIES')
  await page.getByLabel('본사 지역').selectOption('us')
  await expect(page.getByLabel('반도체와 디스플레이 산업 3D 지식맵')).toContainText('20 / 73 COMPANIES')
  await page.getByLabel('본사 지역').selectOption('europe')
  await expect(page.getByLabel('반도체와 디스플레이 산업 3D 지식맵')).toContainText('10 / 73 COMPANIES')
  expect(errors).toEqual([])
})

test('knowledge map remains readable on mobile', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'mobile', '모바일 프로젝트에서만 확인')
  await page.goto('/industry-map/')
  await expect(page.getByRole('heading', { name: '반도체 × 디스플레이 산업 은하' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'SK hynix' })).toBeVisible()
  await expect(page.getByLabel('산업 지식맵 회사 목록')).toBeVisible()
  await page.getByRole('button', { name: '공정 장비표' }).click()
  await expect(page.getByRole('heading', { name: '공정별 장비·소재 생태계' })).toBeVisible()
  await page.getByRole('button', { name: 'Flexible OLED' }).click()
  await expect(page.getByText('OLED 증착', { exact: true })).toBeVisible()
  const bodyWidth = await page.locator('body').evaluate((element) => element.scrollWidth)
  expect(bodyWidth).toBeLessThanOrEqual(page.viewportSize()?.width ?? 390)
  await page.screenshot({ path: testInfo.outputPath('industry-map-mobile.png') })
})

test('continue personal AI dialogue inside an automatic response popup', async ({ page }) => {
  const mockResponse = '가설 1은 챔버 위치 편차, 가설 2는 RF 조건 변화, 가설 3은 측정 편향이다. 위치별 분포와 대조군으로 각각 반증한다.'
  await page.route('**/api/sessions/*/llm/check', (route) => route.fulfill({
    contentType: 'application/json',
    body: JSON.stringify({ status: 'connected', provider: 'gemini', provider_label: 'Google Gemini', model: 'gemini-3.5-flash' }),
  }))
  await page.route('**/api/sessions/*/llm/generate', (route) => route.fulfill({
    contentType: 'application/json',
    body: JSON.stringify({ provider: 'gemini', provider_label: 'Google Gemini', model: 'gemini-3.5-flash', response: mockResponse, usage: { prompt_tokens: 100, completion_tokens: 80, thought_tokens: 45, total_tokens: 225 }, finish_reason: 'STOP', retry_count: 0 }),
  }))
  await page.goto('/#dry-etch-profile')
  await page.getByRole('button', { name: /Lot 보류/ }).click()
  await page.getByRole('button', { name: /판단을 기록하고/ }).click()
  await page.getByLabel('개인 API 키').fill('test-key-with-more-than-20-characters')
  await page.getByRole('button', { name: '1. 연결 확인' }).click()
  await expect(page.getByRole('button', { name: '2. 질문 보내기' })).toBeEnabled()
  await page.getByRole('button', { name: '2. 질문 보내기' }).click()
  const chat = page.getByRole('dialog', { name: 'AI와 공정 문제 좁히기' })
  await expect(chat).toBeVisible()
  await expect(chat).toContainText(mockResponse)
  await expect(chat).toContainText('응답 80 · 사고 45 · 전체 225 tokens')
  await expect(chat).toContainText('1/15회')
  const followUp = chat.getByLabel('다음 질문')
  await expect(followUp).toBeFocused()
  await followUp.fill('Sidewall angle 가설 중 RF bias와 위치 편차를 구분할 최소 반증 데이터는 무엇이야?')
  await chat.getByRole('button', { name: '후속 질문 보내기' }).click()
  await expect(chat).toContainText('2/15회')
  await expect(chat.locator('.chat-answer')).toHaveCount(2)
  await chat.getByRole('button', { name: 'AI 대화창 닫기' }).click()
  const responseField = page.getByLabel('외부 AI 분석 답변 붙여넣기')
  await expect(responseField).toHaveValue(mockResponse)
  await expect(page.getByText(/응답이 자동 입력됐어/)).toBeVisible()
  await responseField.fill(`${mockResponse} 사람이 수정한 문장.`)
  await expect(responseField).toHaveValue(/사람이 수정한 문장/)
})

test('show Gemini request failures inside the dialogue popup', async ({ page }) => {
  await page.route('**/api/sessions/*/llm/check', (route) => route.fulfill({
    contentType: 'application/json',
    body: JSON.stringify({ status: 'connected', provider: 'gemini', provider_label: 'Google Gemini', model: 'gemini-3.5-flash' }),
  }))
  await page.route('**/api/sessions/*/llm/generate', (route) => route.fulfill({
    status: 502,
    contentType: 'application/json',
    body: JSON.stringify({ detail: '제공사 API 요청에 실패했습니다 (400). 제공사 응답: generationConfig 설정을 확인하세요.' }),
  }))
  await page.goto('/#photo-cd-drift')
  await page.getByRole('button', { name: /Lot 보류/ }).click()
  await page.getByRole('button', { name: /판단을 기록하고/ }).click()
  await page.getByLabel('개인 API 키').fill('test-key-with-more-than-20-characters')
  await page.getByRole('button', { name: '1. 연결 확인' }).click()
  await page.getByRole('button', { name: '2. 질문 보내기' }).click()
  const chat = page.getByRole('dialog', { name: 'AI와 공정 문제 좁히기' })
  await expect(chat).toBeVisible()
  await expect(chat).toContainText('새 응답을 받지 못했어')
  await expect(chat).toContainText('generationConfig 설정을 확인하세요.')
  await expect(chat.getByRole('button', { name: '같은 질문 다시 시도' })).toBeVisible()
})
